### PR TITLE
feat(Button): 	Add full width prop

### PR DESCRIPTION
**Pull request by kosanna**

### CODE REVIEW

**Comment by mengtzu** [comment]
👍

**Comment by kosanna** [comment]
🤔  I'd rather add them to button themselves as we're using it multiple times across Chalice

**Comment by mengtzu** [comment]
The issue you'll probably have is buttons you want full width for small screens but not for large.  That's fine if it's easy to mess with their containers, but you won't want to change your prop based on screen size.

**Comment by georgespyropoulos** [comment]
I have that exact use case for something I am working on at the moment - I have a button that I only want to be full width on mobile and the prop doesn't help at all

**Comment by mengtzu** [comment]
Arguably though because it is such a common use case on mobile, mobile-first thinking is to use the prop and desktop can just manipulate a wrapper :)

**Comment by michaeltaranto** [comment]
I think the prop names should be more declarative rather than boolean-esc, eg. `full-width`. Not so sure about the text wrap configuration, our use case is 'interesting' and not sure that the style guide should introduce a supported api for this... yet.

**Comment by kosanna** [comment]
Can I merge this one? :)

**Comment by kosanna** [comment]
@mengtzu? Second approval? 😆

**Pull request merged**
