### PR TITLE
Upgrade to Node v6

### PR DESCRIPTION
**Pull request by markdalgleish**
Since I'm running the latest version of Node, I kept getting warnings about the `--harmony-proxies` CLI flag whenever running the tests. Figured it'd be worth upgrading to the latest version, where proxies are enabled by default, rather than working around it locally.

### CODE REVIEW

**Comment by mengtzu** [comment]
🚀

**Comment by mjt01** [comment]
@markdalgleish interested in the choice between Node 7 and 6 with regard to LTS?

**Comment by markdalgleish** [comment]
@mjt01 interesting—I just went with the latest stable version, but it makes sense to only use even-numbered releases. Should I roll back to v6?

**Comment by markdalgleish** [comment]
@mjt01 decided to roll back to v6 based on LTS, like you said.

**Comment by markdalgleish** [comment]
@mjt01 Unfortunately this means the branch name is incorrect. Do we care, or should I close this and open a new PR?

**Comment by jahredhope** [comment]
Would it be worth adding Node engine requirements to package.json as well?
https://docs.npmjs.com/files/package.json#engines

and/or mention the engine requirements in a `README.md` or `CONTRIBUTING.md`?

**Comment by markdalgleish** [comment]
@jahredhope good point, I think we should add a `CONTRIBUTING.md`. Might raise an issue for this, don't want this PR to grow too might right now.

**Comment by markdalgleish** [comment]
Branch name is wrong, so closing in favour of #86.

**Pull request closed without merging**
