### PR TITLE
fix(less): add px unit to @responsive-breakpoint, try to pretend it w…

### PR DESCRIPTION
**Pull request by mengtzu**
…as always there

### CODE REVIEW

**Comment by markdalgleish** [comment]
Can you rename the commit to `fix(less): Add px unit to @responsive-breakpoint` so it doesn't get clipped?

**Comment by markdalgleish** [comment]
Does this mean that we can remove all the instances of `unit(...)` throughout the style guide?

**Comment by mengtzu** [comment]
@markdalgleish is `unit()` the convention for the styleguide?

**Comment by markdalgleish** [comment]
AFAIK we only use it because we were operating on a numeric variable that didn't have a corresponding unit, wanting to turn it into a pixel value. @mjt01, do you know more about this?

**Comment by mjt01** [comment]
I think @markdalgleish is talking about removing all of these:
```css
@media only screen and (min-width: unit(@responsive-breakpoint, px))
```
The initial intent was modelling these as values and converting them when required, but the logic behind this breakpoint is not a calculation so making it `px` seems fair.

I agree with mark the clean up should be changing all the `unit()` calls to simply use the value now.

**Comment by mengtzu** [comment]
@markdalgleish @mjt01 Sure, I can do that, I'll add it to this PR

**Comment by mengtzu** [comment]
I'll open a new PR with a single commit

**Pull request closed without merging**
