### PR TITLE
fix(accessibility): Accessible sk-green

### PR DESCRIPTION
**Pull request by kaylajheffernan**

### CODE REVIEW

**Comment by kosanna** [comment]
@kaylajheffernan are we AA or AAA?

**Comment by kaylajheffernan** [comment]
@kosanna we aim for minimum AA accessibility which this change meets. 
Some of our other colours will be AAA accessible

**Comment by kosanna** [comment]
It fails AAA. If we're happy with AA, then yay! 👍

**Comment by stephaniemoss** [comment]
@kosanna Yeah, we're just trying to meet AA at the moment :'D

**Comment by markdalgleish** [comment]
@kaylajheffernan happy for me to merge this?

**Pull request merged**
