### PR TITLE
fix(seo):  Nofollow specific Header and Footer links

### PR DESCRIPTION
**Pull request by ychua**
No follow some header and footer links that has low seo values.

REASON FOR CHANGE:

To save some search engine crawl budget by choosing to nofollow low value links

### CODE REVIEW

**Comment by ychua** [comment]
@michaeltaranto yep, sounds good

**Comment by markdalgleish** [comment]
@ychua I checked the Surge preview and noticed that the nofollows aren't being rendered. Looks like you might have missed some files in the commit because, apart from a single line of app code, only the snapshots have changed.

**Comment by michaeltaranto** [comment]
@markdalgleish have checked the preview [on surge](http://seek-style-guide--05fa2a5850879cb02aadf8e9576e37c71744ba78.surge.sh/footer) and seems to be working. FYI it's not all links, only specific ones.

**Comment by markdalgleish** [comment]
I think it's just the existing nofollows you're looking at.

screen shot 2017-10-06 at 10 27 55 am

**Comment by markdalgleish** [comment]
Ignore me, I'm a very confused individual. Carry on.

**Pull request merged**
