### PR TITLE
feat(icons): Add social icons

### PR DESCRIPTION
**Pull request by ryardley**
Adding Social Icons to the Style Guid to create new sharing buttons: 

image

### CODE REVIEW

**Comment by ryardley** [comment]
Question: Seems like a fair bit of boilerplate is creeping in here. Should we create a HOC to output the icon components?

**Comment by markdalgleish** [comment]
The build is currently broken for this PR because forks don't have access to the secure environment variables, which is causing the Surge preview deployment to fail. I'll look into this today.

**Comment by markdalgleish** [comment]
@ryardley nitpick, but could you remove the redundant "to Style Guide" from the end of the commit message and PR title?

**Comment by markdalgleish** [comment]
@ryardley I just updated this branch so it has the build fix to skip the deployment step for fork builds.

**Comment by markdalgleish** [comment]
🎨 👍

**Comment by markdalgleish** [comment]
Oh, and don't forget to tidy up the commit message when merging 😄

**Pull request merged**
