### PR TITLE
docs(readme): Suggest installation as runtime dependency

### PR DESCRIPTION
**Pull request by markdalgleish**
We've somehow missed this until recently, but installing the style guide as a dev dependency can cause issues in server rendered applications when running `npm install --only=production`. This can lead to missing dependencies at runtime, which varies depending on the dependencies of your own application. As a result, we're now recommending that style guide consumers *always* install it as a regular dependency instead.

### CODE REVIEW

**Comment by markdalgleish** [comment]
@michaeltaranto does this look good to you?

**Comment by michaeltaranto** [comment]
Woah! Huge. Yeah taking this for a test spin tomorrow, I got the branch ready this afternoon to test it out.

**Comment by markdalgleish** [comment]
What a troll 😛

**Comment by michaeltaranto** [comment]
Slightly more controversial but once this becomes the norm we should pull the `peerDependency` mess out of `package.json` as that was a stop gap solution for getting around the `devDependency` issue.

**Pull request merged**
