### PR TITLE
Fields subnavigation

### PR DESCRIPTION
**Pull request by mattsjones**

### CODE REVIEW

**Comment by mjt01** [comment]
You forgot to update the static build routes in webpack.gh-pages.server.config.js

**Comment by mattsjones** [comment]
This is what it looks like btw. 

image

**Comment by mjt01** [comment]
Given where it's landed, i feel like this should be updated to: Home, Typography, Components — where Components is a list of Button, Icons, AutoSuggest, TextField etc

**Comment by markdalgleish** [comment]
@mattsjones What's the status of this PR?

**Comment by markdalgleish** [comment]
@mjt01 is this something you're still across, or do we need to wait for Matt?

**Comment by mjt01** [comment]
@markdalgleish this should probably be closed, since then a lot of new components have been added. We need a better solution for the IA of the mini site, not just for fields. Arguably a better starting point would be:

"Home" | "Typography" | "Colours" | "Components"

Where "Components" is a drop down menu. The site is pretty broken right now. Thoughts?

**Comment by markdalgleish** [comment]
@mjt01 agreed that this is a much larger problem that needs a more holistic solution.

**Comment by mengtzu** [comment]
@mjt01 +1 to that suggestion.  A drop-down might become unwieldy with enough components (or even categories of components), but we could deal with that when actually reaching that scale.

**Comment by markdalgleish** [comment]
Spoke with @mattsjones, closing this in favour or more large-scale changes which will hopefully be coming soon.

**Pull request closed without merging**
