### PR TITLE
feat(Checkbox): Allow checkbox to be wrapped in a component passed as a wrapper

### PR DESCRIPTION
**Pull request by kosanna**
Tests update.
Will be passing NavLink for Classifications filter

### CODE REVIEW

**Comment by markdalgleish** [comment]
Sorry, not sure I understand the requirements for this change, might need to take a discussion about this offline first.

**Comment by kosanna** [comment]
@markdalgleish on classifications checked/unchecked we need to track stuff and we need it to use checkbox component from style-guide, so we need to pass a wrapping navlink...as an option we could just try and wrap in locally though...

**Comment by markdalgleish** [comment]
Doesn't this mean that we'll be rendering a *real* checkbox inside of a link?

**Comment by kosanna** [comment]
Not necessary, it could be inside of a div, because navlink accepts components too... actually, it might work if we pass checkbox to navlink as well

**Comment by kosanna** [comment]
Will close it for now and try out a workaround

**Pull request closed without merging**
